import { useCallback, useEffect, useState } from 'react';
import { api } from '../lib/api.js';
import { Icon, Spinner } from './Icon.jsx';
import { Skeleton } from './primitives.jsx';

const TABS = [
  { key: 'summary', label: 'Executive summary', icon: 'sparkles' },
  { key: 'code', label: 'Fix code', icon: 'wrench' },
  { key: 'effects', label: 'Side effects', icon: 'alert' },
  { key: 'playbook', label: 'Playbook', icon: 'list' },
];

const SOURCE = {
  claude: { label: 'Claude', className: 'border-amber-400/30 bg-amber-400/10 text-amber-200' },
  openai: { label: 'OpenAI', className: 'border-emerald-400/30 bg-emerald-400/10 text-emerald-200' },
  rules: { label: 'Rules engine', className: 'border-white/10 bg-white/[0.04] text-slate-300' },
};

function CopyButton({ text }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      setCopied(false);
    }
  };
  return (
    <button type="button" onClick={copy} className="btn-ghost px-2 py-1 text-[11px]" aria-label="Copy code">
      <Icon name={copied ? 'check' : 'copy'} className="h-3.5 w-3.5" /> {copied ? 'Copied' : 'Copy'}
    </button>
  );
}

function Scripts({ scripts }) {
  const [active, setActive] = useState(0);
  const script = scripts[Math.min(active, scripts.length - 1)];
  if (!script) return null;
  return (
    <div className="overflow-hidden rounded-lg border border-white/[0.06] bg-ink-950">
      <div className="flex items-center justify-between gap-2 border-b border-white/[0.06] px-2 py-1.5">
        <div className="flex flex-wrap gap-1" role="tablist">
          {scripts.map((s, i) => (
            <button
              key={`${s.label}-${i}`}
              type="button"
              role="tab"
              aria-selected={i === active}
              onClick={() => setActive(i)}
              className={`rounded-md px-2 py-1 text-[11px] font-medium transition ${i === active ? 'bg-white/[0.08] text-slate-100' : 'text-slate-500 hover:text-slate-300'}`}
            >
              {s.label} <span className="font-mono text-[10px] text-slate-500">{s.language}</span>
            </button>
          ))}
        </div>
        <CopyButton text={script.code} />
      </div>
      <pre className="scrollbar-thin max-h-72 overflow-auto p-3 font-mono text-[11.5px] leading-relaxed text-slate-300"><code>{script.code}</code></pre>
    </div>
  );
}

/** AI-generated analysis for one finding, fetched lazily when the card opens. */
export function InsightPanel({ findingId, rec }) {
  const [tab, setTab] = useState('summary');
  const [insight, setInsight] = useState(null);
  const [error, setError] = useState(null);
  const [loading, setLoading] = useState(false);

  const load = useCallback(async (refresh = false) => {
    setLoading(true);
    setError(null);
    try {
      setInsight(await api.insight(findingId, { refresh }));
    } catch (e) {
      setError(e);
    } finally {
      setLoading(false);
    }
  }, [findingId]);

  useEffect(() => {
    load();
  }, [load]);

  const source = SOURCE[insight?.source] ?? SOURCE.rules;

  return (
    <div className="mt-4 overflow-hidden rounded-xl border border-white/[0.06] bg-ink-950/50">
      <div className="flex flex-wrap items-center justify-between gap-2 border-b border-white/[0.06] px-3 py-2">
        <div className="scrollbar-thin flex gap-1 overflow-x-auto" role="tablist" aria-label="Security Brain analysis">
          {TABS.map((t) => (
            <button
              key={t.key}
              type="button"
              role="tab"
              aria-selected={tab === t.key}
              onClick={() => setTab(t.key)}
              className={`inline-flex shrink-0 items-center gap-1.5 rounded-md px-2.5 py-1.5 text-xs font-medium transition ${
                tab === t.key ? 'bg-white/[0.07] text-white' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Icon name={t.icon} className="h-3.5 w-3.5" /> {t.label}
            </button>
          ))}
        </div>
        {insight && (
          <div className="flex items-center gap-1.5">
            <span
              className={`inline-flex items-center gap-1 rounded-md border px-1.5 py-0.5 text-[10px] font-semibold ${source.className}`}
              title={insight.fallbackReason ?? (insight.model ? `Generated by ${insight.model}` : 'Deterministic Veyra playbook')}
            >
              {insight.source !== 'rules' && <Icon name="sparkles" className="h-3 w-3" />}
              {source.label}{insight.model ? ` · ${insight.model}` : ''}
            </span>
            {insight.fallbackReason && (
              <span className="text-[10px] text-amber-300/80" title={insight.fallbackReason}>AI fallback</span>
            )}
            <button type="button" onClick={() => load(true)} disabled={loading} className="btn-ghost p-1" aria-label="Regenerate analysis" title="Regenerate">
              {loading ? <Spinner className="h-3.5 w-3.5" /> : <Icon name="refresh" className="h-3.5 w-3.5" />}
            </button>
          </div>
        )}
      </div>

      <div className="p-4">
        {error && (
          <div className="flex items-center justify-between gap-3 rounded-lg border border-rose-500/30 bg-rose-500/10 px-3 py-2 text-xs text-rose-200">
            {error.message}
            <button type="button" onClick={() => load()} className="btn-ghost px-2 py-1 text-xs">Retry</button>
          </div>
        )}
        {!insight && !error && (
          <div className="space-y-2" aria-busy="true">
            <p className="flex items-center gap-2 text-xs text-slate-500"><Spinner className="h-3.5 w-3.5" /> Security Brain is analyzing this finding…</p>
            <Skeleton className="h-4 w-11/12" /><Skeleton className="h-4 w-4/5" /><Skeleton className="h-4 w-2/3" />
          </div>
        )}

        {insight && tab === 'summary' && (
          <div className="grid gap-4 md:grid-cols-2">
            <div>
              <p className="eyebrow">For the executive team</p>
              <p className="mt-1.5 text-sm leading-relaxed text-slate-200">{insight.executiveSummary}</p>
            </div>
            <div>
              <p className="eyebrow">Business impact</p>
              <p className="mt-1.5 text-sm leading-relaxed text-slate-300">{insight.businessImpact}</p>
            </div>
          </div>
        )}

        {insight && tab === 'code' && (
          <div className="space-y-2">
            <Scripts scripts={insight.scripts} />
            <p className="text-[11px] text-slate-500">
              Review before running. {insight.autoFix?.supported
                ? 'Auto-Fix applies the equivalent vetted playbook for you, never this generated code.'
                : `Auto-Fix is not available: ${insight.autoFix?.reason}`}
            </p>
          </div>
        )}

        {insight && tab === 'effects' && (
          <div className="space-y-3">
            <p className="eyebrow">Double-check before applying</p>
            <ul className="space-y-2">
              {insight.sideEffects.map((effect) => (
                <li key={effect} className="flex gap-2.5 text-sm text-slate-300">
                  <Icon name="alert" className="mt-0.5 h-4 w-4 shrink-0 text-amber-400" />
                  {effect}
                </li>
              ))}
            </ul>
            {insight.rollback && (
              <div className="rounded-lg border border-white/[0.06] bg-white/[0.02] p-3">
                <p className="eyebrow">Rollback</p>
                <p className="mt-1 break-words font-mono text-xs text-slate-400">{insight.rollback}</p>
              </div>
            )}
          </div>
        )}

        {tab === 'playbook' && (
          <div className="grid gap-4 md:grid-cols-2">
            <div>
              <p className="eyebrow">Remediation steps</p>
              <ol className="mt-2 space-y-2">
                {rec.remediation.map((step, i) => (
                  <li key={step} className="flex gap-2.5 text-sm text-slate-300">
                    <span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-white/[0.06] font-mono text-[10px] text-slate-400">{i + 1}</span>
                    {step}
                  </li>
                ))}
              </ol>
            </div>
            <div>
              <p className="eyebrow">Affected resource</p>
              <p className="mt-1.5 break-all font-mono text-xs text-slate-300">{rec.resource.name}</p>
              <p className="text-xs text-slate-500">{rec.resource.type}</p>
              {rec.autoFix?.permission && (
                <>
                  <p className="eyebrow mt-4">Auto-Fix permission</p>
                  <p className="mt-1.5 font-mono text-xs text-slate-400">{rec.autoFix.permission}</p>
                </>
              )}
              {rec.frameworks?.length > 0 && (
                <>
                  <p className="eyebrow mt-4">Compliance</p>
                  <div className="mt-1.5 flex flex-wrap gap-1.5">
                    {rec.frameworks.map((f) => (
                      <span key={f} className="rounded border border-white/10 px-1.5 py-0.5 text-[11px] text-slate-400">{f}</span>
                    ))}
                  </div>
                </>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
